print('-'*100)
print('LOCAÇÃO DE CARROS ZACARIAS LTDA')
print('PARABÉNS POR USUFRUIR DE NOSSOS SERVIÇOS!\nPara finalizar o pagamento, favor nos informar abaixo')
d=int(input('Quantos dias com o carro alugado: '))
k=float(input('Quantos KM foram rodados: '))
cc=(d*60)
kr=(k*0.15)
tp=(cc+kr)
print('-'*100)
print(' '*40, 'PROCESSANDO')
print('-'*100)
print('Foram {} dias com o carro alugado, sendo a diária de R$ 60,00, totalizando R$ {:.2f}'.format(d, cc))
print('Foram {:.2f} KM rodados, sendo que o KM custa R$ 0,15, totalizando R$ {:.2f}'.format(k, kr))
print('Total a pagar: R$ {:.2f}'.format(tp))